onEvent('item.registry', e => {
	e.create('atm_star').displayName('§6ATM Star').unstackable().glow(true)
	e.create('dimensional_seed').displayName('§6Dimensional Seed').unstackable()
	e.create('dragon_soul').displayName('§6Dragon Soul').unstackable()
	e.create('improbable_probability_device').displayName('§6Improbable Probability Device').unstackable()
	e.create('mass_of_wills').displayName('§6Mass of Wills').tooltip('§fCombination of the six wills of the ancients').unstackable()
	e.create('nexium_emitter').displayName('§6Nexium Emitter').unstackable()
	e.create('oblivion_shard').displayName('§6Oblivion Shard').unstackable()
	e.create('patrick_star').displayName('§dPatrick Star').unstackable()
	e.create('philosophers_fuel').displayName('§6Philosopher\'s Fuel').unstackable()
	e.create('pulsating_black_hole').displayName('§6Pulsating Black Hole').unstackable()
	e.create('rune_of_sins').displayName('§6Rune of Sins').tooltip('§fRune that contains the power of the seven sins').unstackable()
	e.create('withers_compass').displayName('§6Wither\'s Compass').unstackable()

	e.create('rotten_leather').displayName('Rotten Leather')
	e.create('uu_matter').displayName('§dUU-Matter')
	e.create('saltpeter_ingot').displayName('Nitrate Ingot')
	e.create('potassium_nitrate_dust').displayName('Potassium Nitrate Dust')
	e.create('potassium_nitrate_ingot').displayName('Potassium Nitrate Ingot')
	e.create('potassium_dust').displayName('Potassium Dust')
	e.create('potassium_ingot').displayName('Potassium Ingot')
})