#Max number of times you can use /back
#Range: > 0
maxBack = 0
#Max homes
#Range: > 0
maxHomes = 0
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 604800
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 604800
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 604800
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 604800
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 604800
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 10
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 100000.0

