
[Smoke]
	#Default smoke color in ARGB (Alpha, Red, Green, Blue) hex format (0xaarrggbb)
	defaultColor = 0
	#Maximum smoke particles amount per chimney
	#Range: 1 ~ 100
	maxAmount = 16
	#Maximum smoke blow out distance
	#Range: 0.0 ~ 20.0
	maxIntencity = 4.0
	#Maximum smoke particles scale
	#Range: 1.0 ~ 10.0
	maxScale = 2.5
	#Maximum smoke particles render distance
	#Range: 16 ~ 256
	maxRenderDistance = 128

