
[Villages]
	#
	# Add the custom villages to modded biomes of the same categories/type.
	addVillagesToModdedBiomes = true
	#
	# Add the ID/resource location of the biome you don't want
	# RS's village to spawn in. Separate each ID with a comma ,
	#   Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedVillageBiomes = ""

	[Villages.MaxChunkDistance]
		#
		# How rare are Crimson Village in Crimson Forest biomes.
		# 1 for spawning in most chunks and 1001 for none.
		#Range: 1 ~ 1001
		crimsonVillageMaxChunkDistance = 30
		#
		# How rare are Birch Villages in Birch biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		birchVillageMaxChunkDistance = 31
		#
		# How rare are Swamp Villages in Swamp biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		swampVillageMaxChunkDistance = 31
		#
		# How rare are Dark Forest Villages in Dark Forest biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		darkForestVillageMaxChunkDistance = 31
		#
		# How rare are Mountains Villages in Mountains biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		mountainsVillageMaxChunkDistance = 31
		#
		# How rare are Jungle Villages in Jungle biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		jungleVillageMaxChunkDistance = 29
		#
		# How rare are Warped Village in Warped Forest biomes.
		# 1 for spawning in most chunks and 1001 for none.
		#Range: 1 ~ 1001
		warpedVillageMaxChunkDistance = 30
		#
		# How rare are Badlands Villages in Badland biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		badlandsVillageMaxChunkDistance = 23
		#
		# How rare are Giant Taiga Villages in Giant Taiga biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		giantTaigaVillageMaxChunkDistance = 29
		#
		# How rare are Oak Villages in forest category
		# biomes that are not birch or dark forest.
		#Range: 1 ~ 1001
		villageOakMaxChunkDistance = 33

